Repository ROCm/rocAL, pull requests merged in 2024-09, with the labels that each got.

#192 Audio decoder Jupyter NoteBook
  docs/examples/notebooks/audio_decoder.ipynb
Labels: enhancement

#207 Adding fix for negative device_id in pipeline creation
  rocAL/source/api/rocal_api.cpp
  rocAL_pybind/amd/rocal/pipeline.py
Labels: bug fix

#199 Fix external source reader pybind call
  rocAL_pybind/amd/rocal/fn.py
  rocAL_pybind/amd/rocal/readers.py
  tests/python_api/external_source_reader.py
Labels: bug fix

#206 Update pytorch training example
  docs/examples/pytorch/imagenet_training/README.md
  docs/examples/pytorch/imagenet_training/imagenet_training.py
Labels: enhancement

#182 Last Batch Policy changes for file source reader
  rocAL/include/api/rocal_api_data_loaders.h
  rocAL/include/api/rocal_api_info.h
  rocAL/include/api/rocal_api_tensor.h
  rocAL/include/api/rocal_api_types.h
  rocAL/include/loaders/audio/audio_loader.h
  rocAL/include/loaders/audio/audio_loader_sharded.h
  rocAL/include/loaders/audio/audio_read_and_decode.h
  rocAL/include/loaders/audio/node_audio_loader.h
  rocAL/include/loaders/audio/node_audio_loader_single_shard.h
  rocAL/include/loaders/image/node_fused_jpeg_crop.h
  rocAL/include/loaders/image/node_fused_jpeg_crop_single_shard.h
  rocAL/include/loaders/image/node_image_loader.h
  rocAL/include/loaders/image/node_image_loader_single_shard.h
  rocAL/include/meta_data/meta_data_reader.h
  rocAL/include/meta_data/text_file_meta_data_reader.h
  rocAL/include/pipeline/commons.h
  rocAL/include/pipeline/tensor.h
  rocAL/include/readers/file_source_reader.h
  rocAL/include/readers/image/image_reader.h
  rocAL/source/api/rocal_api_data_loaders.cpp
  rocAL/source/loaders/audio/audio_loader.cpp
  rocAL/source/loaders/audio/audio_loader_sharded.cpp
  rocAL/source/loaders/audio/audio_read_and_decode.cpp
  rocAL/source/loaders/audio/audio_source_evaluator.cpp
  rocAL/source/loaders/audio/node_audio_loader.cpp
  rocAL/source/loaders/audio/node_audio_loader_single_shard.cpp
  rocAL/source/loaders/image/node_fused_jpeg_crop.cpp
  rocAL/source/loaders/image/node_fused_jpeg_crop_single_shard.cpp
  rocAL/source/loaders/image/node_image_loader.cpp
  rocAL/source/loaders/image/node_image_loader_single_shard.cpp
  rocAL/source/meta_data/text_file_meta_data_reader.cpp
  rocAL/source/pipeline/tensor.cpp
  rocAL/source/readers/file_source_reader.cpp
  rocAL_pybind/amd/rocal/decoders.py
  rocAL_pybind/amd/rocal/pipeline.py
  rocAL_pybind/amd/rocal/plugin/pytorch.py
  rocAL_pybind/rocal_pybind.cpp
  tests/python_api/audio_unit_test.py
Labels: enhancement

#208 Package - Remove rocdecode dependency
  .github/workflows/linting.yml
  CHANGELOG.md
  CMakeLists.txt
  README.md
  rocAL-setup.py
Labels: enhancement, bug fix

#214 Updated 6.2.1 changelog so that it reflects the 6.2.1 RN
  CHANGELOG.md
Labels: documentation, ci:docs-only
