Repository ROCm/rocAL, pull requests merged in 2024-03, with the labels that each got.

#111 Remove logo
  docs/README.md
Labels: ci:docs-only

#112 fix link
  README.md
Labels: ci:docs-only

#116 Docs - Cherry Pick
  LICENSE.txt
  docs/examples.rst
  docs/how-to/architecture.rst
  docs/how-to/framework.rst
  docs/how-to/index.rst
  docs/how-to/overview.rst
  docs/how-to/using-with-cpp.rst
  docs/how-to/using-with-python.rst
  docs/index.rst
  docs/install/install.rst
  docs/license.md
  docs/license.rst
  docs/sphinx/_toc.yml.in
Labels: enhancement, noCI, bug fix

#115 remove jpegint.h dependency from rocAL
  cmake/FindTurboJpeg.cmake
  docs/README.md
  rocAL/CMakeLists.txt
  rocAL/include/decoders/libjpeg/libjpeg_utils.h
  rocAL/source/decoders/libjpeg/libjpeg_extra.cpp
Labels: bug fix

#113 One hot encoded labels support
  rocAL/include/api/rocal_api_meta_data.h
  rocAL/source/api/rocal_api_meta_data.cpp
  rocAL_pybind/amd/rocal/pipeline.py
  rocAL_pybind/amd/rocal/plugin/generic.py
  rocAL_pybind/amd/rocal/plugin/pytorch.py
  rocAL_pybind/amd/rocal/plugin/tf.py
  rocAL_pybind/examples/PYTHON_UNITTEST_TEST_FILE.sh
  rocAL_pybind/examples/image_comparison.py
  rocAL_pybind/examples/parse_config.py
  rocAL_pybind/examples/rocAL_api_python_unittest.py
  rocAL_pybind/examples/rocAL_api_tf_classification_reader.py
  rocAL_pybind/rocal_pybind.cpp
  tests/cpp_api_tests/rocAL_unittests/rocAL_unittests.cpp
Labels: enhancement

#117 rocAL Fix video flag
  rocAL/include/pipeline/master_graph.h
Labels: bug fix
