Repository ROCm/rocAL, pull requests merged in 2024-05, with the labels that each got.

#148 Cupy import fix
  rocAL_pybind/amd/rocal/plugin/generic.py
  rocAL_pybind/amd/rocal/plugin/tf.py
Labels: bug fix

#140 Adding last batch policy for image loaders
  rocAL/include/api/rocal_api_data_loaders.h
  rocAL/include/api/rocal_api_info.h
  rocAL/include/api/rocal_api_types.h
  rocAL/include/loaders/image/image_loader.h
  rocAL/include/loaders/image/image_loader_sharded.h
  rocAL/include/loaders/image/image_read_and_decode.h
  rocAL/include/loaders/image/node_fused_jpeg_crop.h
  rocAL/include/loaders/image/node_fused_jpeg_crop_single_shard.h
  rocAL/include/loaders/image/node_image_loader.h
  rocAL/include/loaders/image/node_image_loader_single_shard.h
  rocAL/include/loaders/loader_module.h
  rocAL/include/pipeline/commons.h
  rocAL/include/pipeline/master_graph.h
  rocAL/include/readers/file_source_reader.h
  rocAL/include/readers/image/image_reader.h
  rocAL/source/api/rocal_api_data_loaders.cpp
  rocAL/source/api/rocal_api_info.cpp
  rocAL/source/loaders/image/image_loader.cpp
  rocAL/source/loaders/image/image_loader_sharded.cpp
  rocAL/source/loaders/image/image_read_and_decode.cpp
  rocAL/source/loaders/image/node_fused_jpeg_crop.cpp
  rocAL/source/loaders/image/node_fused_jpeg_crop_single_shard.cpp
  rocAL/source/loaders/image/node_image_loader.cpp
  rocAL/source/loaders/image/node_image_loader_single_shard.cpp
  rocAL/source/pipeline/master_graph.cpp
  rocAL/source/readers/file_source_reader.cpp
  rocAL_pybind/amd/rocal/decoders.py
  rocAL_pybind/amd/rocal/pipeline.py
  rocAL_pybind/amd/rocal/plugin/pytorch.py
  rocAL_pybind/amd/rocal/types.py
  rocAL_pybind/rocal_pybind.cpp
Labels: enhancement

#152 ROCm 6.2 updates
  CHANGELOG.md
  CMakeLists.txt
  README.md
  docker/rocal-on-rhel-09.dockerfile
  docker/rocal-on-ubuntu-20-with-pytorch-with-mesa.dockerfile
  docker/rocal-on-ubuntu-20.dockerfile
  docker/rocal-on-ubuntu-22.dockerfile
  docker/rocal-with-pytorch.dockerfile
  docker/rocal-with-tensorflow.dockerfile
  docs/install/install.rst
  rocAL-setup.py
  rocAL/CMakeLists.txt
Labels: enhancement, bug fix

#153 Readme - Updates
  CHANGELOG.md
  CMakeLists.txt
  README.md
  docker/README.md
  docs/install/install.rst
  rocAL-setup.py
Labels: enhancement, bug fix

#158 Update Read the Docs configuration to use Python 3.10 and latest rocm-docs-core
  .github/CODEOWNERS
  .readthedocs.yaml
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: documentation, dependencies, ci:docs-only
