Repository ROCm/rocAL, pull requests merged in 2024-04, with the labels that each got.

#121 rocAL - Add pytorch training example
  docs/examples/pytorch/imagenet_training/README.md
  docs/examples/pytorch/imagenet_training/imagenet_training.py
Labels: enhancement

#114 Generic name change - To maintain a generic name instead of "image"
  rocAL/include/loaders/circular_buffer.h
  rocAL/include/loaders/image/cifar10_data_loader.h
  rocAL/include/loaders/image/image_loader.h
  rocAL/include/loaders/image/image_loader_sharded.h
  rocAL/include/loaders/image/image_read_and_decode.h
  rocAL/include/loaders/loader_module.h
  rocAL/include/loaders/video/video_loader.h
  rocAL/include/loaders/video/video_loader_sharded.h
  rocAL/include/loaders/video/video_read_and_decode.h
  rocAL/include/meta_data/bounding_box_graph.h
  rocAL/include/meta_data/coco_meta_data_reader.h
  rocAL/include/meta_data/coco_meta_data_reader_key_points.h
  rocAL/include/meta_data/meta_data_graph.h
  rocAL/include/pipeline/master_graph.h
  rocAL/include/pipeline/timing_debug.h
  rocAL/source/loaders/circular_buffer.cpp
  rocAL/source/loaders/image/cifar10_data_loader.cpp
  rocAL/source/loaders/image/image_loader.cpp
  rocAL/source/loaders/image/image_loader_sharded.cpp
  rocAL/source/loaders/video/video_loader.cpp
  rocAL/source/loaders/video/video_loader_sharded.cpp
  rocAL/source/meta_data/bounding_box_graph.cpp
  rocAL/source/pipeline/master_graph.cpp
Labels: enhancement

#131 rocAL V2.0.0 - Updates and fixes
  .github/CODEOWNERS
  .github/workflows/linting.yml
  .jenkins/common.groovy
  CHANGELOG.md
  CMakeLists.txt
  README.md
  docker/README.md
  docker/rocal-with-pytorch.dockerfile
  docker/rocal-with-tensorflow.dockerfile
  docs/examples/pytorch/imagenet_training/README.md
  rocAL/CMakeLists.txt
  rocAL_pybind/CMakeLists.txt
  rocAL_pybind/getrocALwheelname.py
  rocAL_pybind/setup.py
  tests/cpp_api/CMakeLists.txt
  tests/cpp_api/basic_test/CMakeLists.txt
  tests/cpp_api/dataloader/CMakeLists.txt
  tests/cpp_api/dataloader_multithread/CMakeLists.txt
  tests/cpp_api/dataloader_tf/CMakeLists.txt
  tests/cpp_api/external_source/CMakeLists.txt
  tests/cpp_api/image_augmentation/CMakeLists.txt
  tests/cpp_api/performance_tests/CMakeLists.txt
  tests/cpp_api/performance_tests_with_depth/CMakeLists.txt
  tests/cpp_api/unit_tests/CMakeLists.txt
  tests/cpp_api/video_tests/CMakeLists.txt
Labels: enhancement, bug fix

#134 Update index.rst
  docs/index.rst
Labels: ci:docs-only

#135 rocAL - Setup updates
  CHANGELOG.md
  README.md
  rocAL-setup.py
  rocAL_pybind/setup.py
Labels: enhancement, bug fix

#138 Update rocAL-setup.py
  rocAL-setup.py
Labels: bug fix

#120 Audio PR - rocAL Python changes for Audio Decoder
  CHANGELOG.md
  rocAL/include/loaders/circular_buffer.h
  rocAL/source/loaders/audio/audio_loader.cpp
  rocAL/source/loaders/audio/audio_read_and_decode.cpp
  rocAL_pybind/amd/rocal/decoders.py
  rocAL_pybind/amd/rocal/plugin/pytorch.py
  rocAL_pybind/rocal_pybind.cpp
  tests/python_api/README.md
  tests/python_api/audio_unit_test.py
  tests/python_api/parse_config.py
Labels: enhancement

#139 Update CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#141 Docs: fix broken links
  docs/how-to/framework.rst
  docs/how-to/using-with-python.rst
  docs/index.rst
  docs/sphinx/_toc.yml.in
Labels: documentation, ci:docs-only

#143 Add 6.1.0 link fix to develop
  docs/how-to/framework.rst
  docs/how-to/using-with-python.rst
Labels: documentation, noCI, ci:docs-only
