Repository ROCm/rocAL, pull requests merged in 2024-12, with the labels that each got.

#241 CMakeLists - Compiler & CMake Version Updates
  CHANGELOG.md
  CMakeLists.txt
  README.md
  docs/install/install.rst
  rocAL-setup.py
  rocAL/CMakeLists.txt
  rocAL/rocAL_hip/CMakeLists.txt
  rocAL_pybind/CMakeLists.txt
  tests/cpp_api/CMakeLists.txt
  tests/cpp_api/audio_tests/CMakeLists.txt
  tests/cpp_api/basic_test/CMakeLists.txt
  tests/cpp_api/dataloader/CMakeLists.txt
  tests/cpp_api/dataloader_multithread/CMakeLists.txt
  tests/cpp_api/dataloader_tf/CMakeLists.txt
  tests/cpp_api/external_source/CMakeLists.txt
  tests/cpp_api/image_augmentation/CMakeLists.txt
  tests/cpp_api/performance_tests/CMakeLists.txt
  tests/cpp_api/performance_tests_with_depth/CMakeLists.txt
  tests/cpp_api/unit_tests/CMakeLists.txt
  tests/cpp_api/video_tests/CMakeLists.txt
  tests/pybind/CMakeLists.txt
Labels: enhancement, bug fix, ci:precheckin

#239 Fix errors wrt latest FFmpeg versions
  cmake/FindFFmpeg.cmake
  rocAL/CMakeLists.txt
  rocAL/include/decoders/image/hw_jpeg_decoder.h
  rocAL/include/decoders/video/ffmpeg_video_decoder.h
  rocAL/include/decoders/video/hardware_video_decoder.h
  rocAL/source/decoders/image/hw_jpeg_decoder.cpp
  rocAL/source/readers/video/video_properties.cpp
Labels: bug fix, ci:precheckin

#249 commit of the RNNT topic
  docs/index.rst
  docs/reference/rocAL-and-RNNT.rst
  docs/sphinx/_toc.yml.in
Labels: documentation, ci:docs-only

#251 Fix GPU pipeline errors wrt AMD Clang++
  rocAL/source/pipeline/graph.cpp
  rocAL/source/pipeline/master_graph.cpp
Labels: bug fix, ci:precheckin
