Repository ROCm/rocAL, pull requests merged in 2024-08, with the labels that each got.

#187 Docs - Fix a few erroneous links to the examples directory
  docs/how-to/framework.rst
  docs/how-to/overview.rst
  docs/user_guide/ch1.md
Labels: ci:docs-only

#188 Setup - SLES 15 SP5 Updates
  CHANGELOG.md
  README.md
  rocAL-setup.py
Labels: enhancement, bug fix

#186 Audio readme update
  docs/README.md
Labels: enhancement

#201 CI: Run python setup as sudo
  .jenkins/common.groovy
Labels: ci:precheckin

#181 Spectrogram example notebook
  docs/examples/notebooks/spectrogram.ipynb
Labels: enhancement
