Repository ROCm/rocAL, pull requests merged in 2024-10, with the labels that each got.

#216 Fix Last Batch Policy PR
  rocAL/source/readers/file_source_reader.cpp
Labels: ci:precheckin

#218 Update clang path similar to reflect packaging
  rocAL/rocAL_hip/CMakeLists.txt
Labels: bug fix, ci:precheckin

#210 rocAL Audio unit test minor fix
  rocAL/source/readers/file_source_reader.cpp
  tests/cpp_api/audio_tests/audio_tests.cpp
  tests/python_api/audio_unit_test.py
Labels: bug fix, ci:precheckin

#221 PyBind - Packaging and CTests
  CHANGELOG.md
  README.md
  rocAL/CMakeLists.txt
  rocAL_pybind/CMakeLists.txt
  rocAL_pybind/getrocALwheelname.py
  rocAL_pybind/setup.py
  tests/pybind/CMakeLists.txt
  tests/pybind/decoders_test.py
  tests/pybind/functions_test.py
  tests/pybind/pipelines_test.py
  tests/pybind/randoms_test.py
  tests/pybind/readers_test.py
  tests/pybind/types_test.py
Labels: enhancement, bug fix, ci:precheckin

#217 Add Last batch policy support for remaining image readers
  CHANGELOG.md
  rocAL/include/api/rocal_api_types.h
  rocAL/include/readers/file_source_reader.h
  rocAL/include/readers/image/caffe2_lmdb_record_reader.h
  rocAL/include/readers/image/caffe_lmdb_record_reader.h
  rocAL/include/readers/image/cifar10_data_reader.h
  rocAL/include/readers/image/coco_file_source_reader.h
  rocAL/include/readers/image/image_reader.h
  rocAL/include/readers/image/mxnet_recordio_reader.h
  rocAL/include/readers/image/tf_record_reader.h
  rocAL/source/readers/file_source_reader.cpp
  rocAL/source/readers/image/caffe2_lmdb_record_reader.cpp
  rocAL/source/readers/image/caffe_lmdb_record_reader.cpp
  rocAL/source/readers/image/cifar10_data_reader.cpp
  rocAL/source/readers/image/coco_file_source_reader.cpp
  rocAL/source/readers/image/image_reader.cpp
  rocAL/source/readers/image/mxnet_recordio_reader.cpp
  rocAL/source/readers/image/tf_record_reader.cpp
  rocAL_pybind/amd/rocal/decoders.py
  rocAL_pybind/amd/rocal/fn.py
  rocAL_pybind/amd/rocal/readers.py
  rocAL_pybind/rocal_pybind.cpp
  tests/python_api/external_source_reader.py
Labels: enhancement, ci:precheckin

#226 updated the changelog for 6.3
  CHANGELOG.md
Labels: documentation, ci:docs-only

#227 CHANGELOG Updates
  CHANGELOG.md
  CMakeLists.txt
  README.md
  rocAL_pybind/getrocALwheelname.py
  rocAL_pybind/setup.py
Labels: enhancement, bug fix, ci:docs-only
