Repository ROCm/rocAL, pull requests merged in 2024-07, with the labels that each got.

#174 CMakeLists - AMDGPU_TARGETS Updates
  CMakeLists.txt
  rocAL/CMakeLists.txt
Labels: enhancement, bug fix

#177 Cherry pick docs 6.2
  .github/CODEOWNERS
  .github/workflows/linting.yml
  .readthedocs.yaml
  docs/README.md
  docs/how-to/framework.rst
  docs/how-to/using-with-python.rst
  docs/index.rst
  docs/install/install.rst
  docs/sphinx/_toc.yml.in
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: documentation, ci:docs-only

#175 Update documentation link
  docs/user_guide/ch3.md
Labels: documentation

#130 Audio PR - Augmentation support [ Mel-Filter Bank and Normalize ]
  CHANGELOG.md
  rocAL/include/api/rocal_api_augmentation.h
  rocAL/include/api/rocal_api_types.h
  rocAL/include/augmentations/audio_augmentations/node_mel_filter_bank.h
  rocAL/include/augmentations/augmentations_nodes.h
  rocAL/include/augmentations/effects_augmentations/node_normalize.h
  rocAL/source/api/rocal_api_augmentation.cpp
  rocAL/source/augmentations/audio_augmentations/node_mel_filter_bank.cpp
  rocAL/source/augmentations/effects_augmentations/node_normalize.cpp
  rocAL_pybind/amd/rocal/fn.py
  rocAL_pybind/amd/rocal/types.py
  rocAL_pybind/rocal_pybind.cpp
  tests/cpp_api/audio_tests/README.md
  tests/cpp_api/audio_tests/audio_tests.cpp
  tests/cpp_api/audio_tests/audio_tests.py
  tests/python_api/README.md
  tests/python_api/audio_unit_test.py
Labels: enhancement

#179 Updating TF pets training example
  docker/rocal-with-tensorflow.dockerfile
  docs/examples/tf/pets_training/README.md
  docs/examples/tf/pets_training/create_pet_tf_record.py
  docs/examples/tf/pets_training/download_and_preprocess_dataset.sh
  docs/examples/tf/pets_training/pet_label_map.pbtxt
  docs/examples/tf/pets_training/requirements.sh
  docs/examples/tf/pets_training/train.py
  rocAL_pybind/amd/rocal/plugin/tf.py
Labels: enhancement
