Repository ROCm/rocAL, pull requests merged in 2024-06, with the labels that each got.

#161 Update framework.rst
  docs/how-to/framework.rst
Labels: documentation, ci:docs-only

#162 Update framework.rst
  docs/how-to/framework.rst
Labels: documentation, ci:docs-only

#160 Update framework.rst
  docs/how-to/framework.rst
Labels: documentation, ci:docs-only

#164 Setup - Updates
  CHANGELOG.md
  CMakeLists.txt
  README.md
  rocAL-setup.py
Labels: enhancement, bug fix

#122 Audio PR - Augmentation support [PreEmphasis Filter]
  CHANGELOG.md
  rocAL/include/api/rocal_api_augmentation.h
  rocAL/include/api/rocal_api_types.h
  rocAL/include/augmentations/audio_augmentations/node_preemphasis_filter.h
  rocAL/include/augmentations/augmentations_nodes.h
  rocAL/source/api/rocal_api_augmentation.cpp
  rocAL/source/augmentations/audio_augmentations/node_preemphasis_filter.cpp
  rocAL_pybind/amd/rocal/fn.py
  rocAL_pybind/amd/rocal/types.py
  rocAL_pybind/rocal_pybind.cpp
  tests/cpp_api/audio_tests/README.md
  tests/cpp_api/audio_tests/audio_tests.cpp
  tests/cpp_api/audio_tests/audio_tests.py
  tests/python_api/README.md
  tests/python_api/audio_unit_test.py
  tests/python_api/parse_config.py
Labels: enhancement

#165 Readme - Updates
  README.md
Labels: enhancement

#123 Audio PR - Adding support for file list reader
  CHANGELOG.md
  rocAL/include/api/rocal_api_data_loaders.h
  rocAL/include/api/rocal_api_meta_data.h
  rocAL/include/readers/file_source_reader.h
  rocAL/include/readers/image/image_reader.h
  rocAL/source/api/rocal_api_data_loaders.cpp
  rocAL/source/api/rocal_api_meta_data.cpp
  rocAL/source/loaders/audio/node_audio_loader.cpp
  rocAL/source/loaders/audio/node_audio_loader_single_shard.cpp
  rocAL/source/meta_data/text_file_meta_data_reader.cpp
  rocAL/source/pipeline/master_graph.cpp
  rocAL/source/readers/file_source_reader.cpp
  rocAL_pybind/amd/rocal/decoders.py
  rocAL_pybind/amd/rocal/plugin/pytorch.py
  rocAL_pybind/amd/rocal/readers.py
  tests/cpp_api/audio_tests/audio_tests.cpp
  tests/cpp_api/audio_tests/audio_tests.py
  tests/python_api/audio_unit_test.py
  tests/python_api/parse_config.py
Labels: enhancement

#124 Audio PR - Augmentation support [ Spectrogram ]
  CHANGELOG.md
  rocAL/include/api/rocal_api_augmentation.h
  rocAL/include/api/rocal_api_types.h
  rocAL/include/augmentations/audio_augmentations/node_spectrogram.h
  rocAL/include/augmentations/augmentations_nodes.h
  rocAL/include/pipeline/commons.h
  rocAL/include/pipeline/tensor.h
  rocAL/source/api/rocal_api_augmentation.cpp
  rocAL/source/api/rocal_api_data_loaders.cpp
  rocAL/source/augmentations/audio_augmentations/node_spectrogram.cpp
  rocAL_pybind/amd/rocal/fn.py
  rocAL_pybind/amd/rocal/types.py
  rocAL_pybind/rocal_pybind.cpp
  tests/cpp_api/audio_tests/README.md
  tests/cpp_api/audio_tests/audio_tests.cpp
  tests/cpp_api/audio_tests/audio_tests.py
  tests/python_api/README.md
  tests/python_api/audio_unit_test.py
Labels: enhancement

#167 Fix org used for linting workflow by rocm-docs-core
  .github/workflows/linting.yml
Labels: documentation, dependencies, ci:docs-only

#125 Audio PR - Augmentation support [ Downmix and ToDecibels ]
  CHANGELOG.md
  rocAL/include/api/rocal_api_augmentation.h
  rocAL/include/api/rocal_api_types.h
  rocAL/include/augmentations/audio_augmentations/node_downmix.h
  rocAL/include/augmentations/audio_augmentations/node_to_decibels.h
  rocAL/include/augmentations/augmentations_nodes.h
  rocAL/include/pipeline/tensor.h
  rocAL/source/api/rocal_api_augmentation.cpp
  rocAL/source/api/rocal_api_data_loaders.cpp
  rocAL/source/augmentations/audio_augmentations/node_downmix.cpp
  rocAL/source/augmentations/audio_augmentations/node_to_decibels.cpp
  rocAL_pybind/amd/rocal/fn.py
  rocAL_pybind/rocal_pybind.cpp
  tests/cpp_api/audio_tests/README.md
  tests/cpp_api/audio_tests/audio_tests.cpp
  tests/cpp_api/audio_tests/audio_tests.py
  tests/python_api/README.md
  tests/python_api/audio_unit_test.py
Labels: enhancement

#127 Audio PR - Augmentation support [ Resample, Operator overloading and Uniform + Normal Distribution nodes ]
  CHANGELOG.md
  rocAL/include/api/rocal_api_augmentation.h
  rocAL/include/augmentations/arithmetic_augmentations/node_tensor_add_tensor.h
  rocAL/include/augmentations/arithmetic_augmentations/node_tensor_mul_scalar.h
  rocAL/include/augmentations/audio_augmentations/node_resample.h
  rocAL/include/augmentations/augmentations_nodes.h
  rocAL/include/augmentations/node_normal_distribution.h
  rocAL/include/augmentations/node_uniform_distribution.h
  rocAL/include/pipeline/commons.h
  rocAL/include/pipeline/master_graph.h
  rocAL/source/api/rocal_api_augmentation.cpp
  rocAL/source/augmentations/arithmetic_augmentations/node_tensor_add_tensor.cpp
  rocAL/source/augmentations/arithmetic_augmentations/node_tensor_mul_scalar.cpp
  rocAL/source/augmentations/audio_augmentations/node_resample.cpp
  rocAL/source/augmentations/node_normal_distribution.cpp
  rocAL/source/augmentations/node_uniform_distribution.cpp
  rocAL_pybind/amd/rocal/fn.py
  rocAL_pybind/amd/rocal/random.py
  rocAL_pybind/rocal_pybind.cpp
  tests/cpp_api/audio_tests/README.md
  tests/cpp_api/audio_tests/audio_tests.cpp
  tests/cpp_api/audio_tests/audio_tests.py
  tests/python_api/README.md
  tests/python_api/audio_unit_test.py
Labels: enhancement

#170 CentOS 7 - Support
  CHANGELOG.md
  CMakeLists.txt
  README.md
  cmake/FindTurboJpeg.cmake
  rocAL-setup.py
Labels: enhancement, bug fix

#172 SLES 15 SP5 - support updates
  CHANGELOG.md
  README.md
  rocAL-setup.py
Labels: enhancement, bug fix

#128 Audio PR - Augmentation support [ NonSilentRegionDetection and Slice ]
  CHANGELOG.md
  rocAL/include/api/rocal_api_augmentation.h
  rocAL/include/api/rocal_api_types.h
  rocAL/include/augmentations/audio_augmentations/node_non_silent_region_detection.h
  rocAL/include/augmentations/augmentations_nodes.h
  rocAL/include/augmentations/geometry_augmentations/node_slice.h
  rocAL/source/api/rocal_api_augmentation.cpp
  rocAL/source/augmentations/audio_augmentations/node_non_silent_region_detection.cpp
  rocAL/source/augmentations/geometry_augmentations/node_slice.cpp
  rocAL/source/pipeline/tensor.cpp
  rocAL_pybind/amd/rocal/fn.py
  rocAL_pybind/amd/rocal/plugin/pytorch.py
  rocAL_pybind/amd/rocal/types.py
  rocAL_pybind/rocal_pybind.cpp
  tests/cpp_api/audio_tests/README.md
  tests/cpp_api/audio_tests/audio_tests.cpp
  tests/cpp_api/audio_tests/audio_tests.py
  tests/python_api/README.md
  tests/python_api/audio_unit_test.py
Labels: enhancement
