Repository ROCm/rocAL, pull requests merged in 2025-05, with the labels that each got.

#327 CIFAR10 reader - multi sharding support
  rocAL/include/api/rocal_api_data_loaders.h
  rocAL/include/loaders/image/cifar10_loader.h
  rocAL/include/loaders/image/cifar10_loader_sharded.h
  rocAL/include/loaders/image/node_cifar10_loader.h
  rocAL/include/loaders/image/node_cifar10_loader_single_shard.h
  rocAL/include/pipeline/master_graph.h
  rocAL/source/api/rocal_api_data_loaders.cpp
  rocAL/source/loaders/image/cifar10_loader.cpp
  rocAL/source/loaders/image/cifar10_loader_sharded.cpp
  rocAL/source/loaders/image/node_cifar10_loader.cpp
  rocAL/source/loaders/image/node_cifar10_loader_single_shard.cpp
  rocAL/source/readers/image/cifar10_data_reader.cpp
  rocAL_pybind/amd/rocal/readers.py
  rocAL_pybind/rocal_pybind.cpp
  tests/cpp_api/dataloader/dataloader.cpp
  tests/python_api/README.md
  tests/python_api/cifar10_reader.py
Labels: enhancement, ci:precheckin

#333 fixed a bad github link
  docs/install/rocAL-build-and-install.rst
Labels: documentation, ci:docs-only

#329 rocAL External source reader C++ test fix
  rocAL/source/loaders/image/image_loader.cpp
  tests/cpp_api/external_source/external_source.cpp
Labels: bug fix, ci:precheckin

#328 Augmentation support - Log1p
  rocAL/include/api/rocal_api_augmentation.h
  rocAL/include/api/rocal_api_types.h
  rocAL/include/augmentations/arithmetic_augmentations/node_log1p.h
  rocAL/include/augmentations/augmentations_nodes.h
  rocAL/include/pipeline/commons.h
  rocAL/include/pipeline/tensor.h
  rocAL/source/api/rocal_api_augmentation.cpp
  rocAL/source/augmentations/arithmetic_augmentations/node_log1p.cpp
  rocAL_pybind/amd/rocal/fn.py
  rocAL_pybind/amd/rocal/types.py
  rocAL_pybind/rocal_pybind.cpp
  tests/python_api/numpy_reader.py
Labels: enhancement, ci:precheckin
