Repository ROCm/rocAL, pull requests merged in 2025-04, with the labels that each got.

#311 CMakeLists - Support Debian OS
  CMakeLists.txt
Labels: enhancement, ci:precheckin

#310 Remove libjpeg check in CMake
  cmake/FindTurboJpeg.cmake
Labels: enhancement, bug fix, ci:precheckin

#302 ROCm 6.4.X: Cherry Pick - update dlpack package to match develop branch
  rocAL-setup.py
Labels: bug fix, ci:precheckin

#314 CTest - check rocDecode version
  cmake/FindrocDecode.cmake
  rocAL/CMakeLists.txt
  tests/cpp_api/CMakeLists.txt
Labels: bug fix, ci:precheckin

#317 Jenkins - Code Coverage
  .jenkins/common.groovy
Labels: enhancement, ci:precheckin

#319 Code cov - add cpp unit tests to code cov
  .jenkins/common.groovy
Labels: enhancement, ci:precheckin

#320 Add audio tests to CI
  .jenkins/common.groovy
Labels: enhancement, ci:precheckin

#321 C++ unit test changes
  rocAL/source/api/rocal_api_meta_data.cpp
  tests/cpp_api/unit_tests/testAllScripts.sh
  tests/cpp_api/unit_tests/unit_tests.cpp
Labels: enhancement, ci:precheckin

#316 Rename TF namespace in protos
  rocAL/include/readers/image/tf_record_reader.h
  rocAL/proto/example.proto
  rocAL/proto/feature.proto
  rocAL/source/meta_data/tf_meta_data_reader.cpp
  rocAL/source/meta_data/tf_meta_data_reader_detection.cpp
Labels: enhancement, ci:precheckin

#322 Code Cov - Python API tests
  .jenkins/common.groovy
  rocAL_pybind/CMakeLists.txt
Labels: enhancement, ci:precheckin

#323 Code coverage - improvements
  .jenkins/common.groovy
  rocAL/include/pipeline/image.h
  rocAL/source/pipeline/image.cpp
  tests/cpp_api/image_augmentation/CMakeLists.txt
  tests/cpp_api/unit_tests/pixel_comparison/image_comparison.py
  tests/cpp_api/unit_tests/testAllScripts.sh
  tests/cpp_api/unit_tests/unit_tests.cpp
Labels: enhancement, ci:precheckin

#325 CXX Standard - Updates
  CMakeLists.txt
  rocAL/CMakeLists.txt
  rocAL/rocAL_hip/CMakeLists.txt
  rocAL_pybind/CMakeLists.txt
  tests/cpp_api/CMakeLists.txt
  tests/cpp_api/audio_tests/CMakeLists.txt
  tests/cpp_api/basic_test/CMakeLists.txt
  tests/cpp_api/dataloader/CMakeLists.txt
  tests/cpp_api/dataloader_multithread/CMakeLists.txt
  tests/cpp_api/dataloader_tf/CMakeLists.txt
  tests/cpp_api/external_source/CMakeLists.txt
  tests/cpp_api/image_augmentation/CMakeLists.txt
  tests/cpp_api/performance_tests/CMakeLists.txt
  tests/cpp_api/performance_tests_with_depth/CMakeLists.txt
  tests/cpp_api/unit_tests/CMakeLists.txt
  tests/cpp_api/video_tests/CMakeLists.txt
Labels: enhancement, ci:precheckin

#326 Remove HW_JPEG_DECODER and codecov improvements
  .jenkins/common.groovy
  rocAL/include/api/rocal_api_types.h
  rocAL/include/decoders/image/decoder.h
  rocAL/include/decoders/image/hw_jpeg_decoder.h
  rocAL/source/api/rocal_api_data_loaders.cpp
  rocAL/source/decoders/image/decoder_factory.cpp
  rocAL/source/decoders/image/hw_jpeg_decoder.cpp
  rocAL_pybind/amd/rocal/types.py
  rocAL_pybind/rocal_pybind.cpp
  tests/cpp_api/unit_tests/testAllScripts.sh
  tests/cpp_api/unit_tests/unit_tests.cpp
Labels: enhancement, ci:precheckin
