Repository ROCm/rocAL, pull requests merged in 2025-03, with the labels that each got.

#294 ROCm 6.4 - Cherrypick: updated changelog
  CHANGELOG.md
Labels: documentation, ci:docs-only

#299 Test - Fix README inconsistencies
  tests/cpp_api/unit_tests/README.md
  tests/python_api/README.md
Labels: bug fix, ci:docs-only

#296 Deps update: Support turbojpeg package
  CHANGELOG.md
  README.md
  rocAL-setup.py
  rocAL/source/decoders/image/turbo_jpeg_decoder.cpp
  rocAL/source/decoders/libjpeg/libjpeg_extra.cpp
Labels: enhancement, ci:precheckin

#291 Numpy reader - C++ changes
  rocAL/include/api/rocal_api_data_loaders.h
  rocAL/include/api/rocal_api_types.h
  rocAL/include/loaders/numpy_source_evaluator.h
  rocAL/include/pipeline/commons.h
  rocAL/include/pipeline/tensor.h
  rocAL/include/readers/image/image_reader.h
  rocAL/include/readers/image/numpy_data_reader.h
  rocAL/source/api/rocal_api_data_loaders.cpp
  rocAL/source/loaders/image/numpy_loader.cpp
  rocAL/source/loaders/numpy_source_evaluator.cpp
  rocAL/source/pipeline/tensor.cpp
  rocAL/source/readers/image/numpy_data_reader.cpp
  rocAL/source/readers/image/reader_factory.cpp
  tests/cpp_api/unit_tests/unit_tests.cpp
Labels: enhancement, ci:precheckin

#304 CTest - Adding ctest for rocdecode integration
  tests/cpp_api/CMakeLists.txt
Labels: enhancement, ci:precheckin

#284 rocAL rocJpeg Integration
  CHANGELOG.md
  CMakeLists.txt
  README.md
  docs/install/install.rst
  docs/user_guide/ch1.md
  rocAL-setup.py
  rocAL/CMakeLists.txt
  rocAL/include/api/rocal_api_types.h
  rocAL/include/decoders/image/decoder.h
  rocAL/include/decoders/image/rocjpeg_decoder.h
  rocAL/include/loaders/circular_buffer.h
  rocAL/include/loaders/image/image_loader.h
  rocAL/include/loaders/image/image_read_and_decode.h
  rocAL/rocAL_hip/rocal_hip_kernels.cpp
  rocAL/rocAL_hip/rocal_hip_kernels.h
  rocAL/source/api/rocal_api_data_loaders.cpp
  rocAL/source/decoders/image/decoder_factory.cpp
  rocAL/source/decoders/image/rocjpeg_decoder.cpp
  rocAL/source/loaders/circular_buffer.cpp
  rocAL/source/loaders/image/image_loader.cpp
  rocAL/source/loaders/image/image_read_and_decode.cpp
  rocAL_pybind/amd/rocal/decoders.py
  rocAL_pybind/amd/rocal/types.py
  rocAL_pybind/rocal_pybind.cpp
  tests/cpp_api/CMakeLists.txt
  tests/cpp_api/basic_test/README.md
  tests/cpp_api/basic_test/basic_test.cpp
Labels: enhancement, ci:precheckin

#292 Numpy reader - python changes
  CHANGELOG.md
  rocAL_pybind/amd/rocal/pipeline.py
  rocAL_pybind/amd/rocal/plugin/generic.py
  rocAL_pybind/amd/rocal/plugin/pytorch.py
  rocAL_pybind/amd/rocal/readers.py
  rocAL_pybind/amd/rocal/types.py
  rocAL_pybind/rocal_pybind.cpp
  tests/python_api/README.md
  tests/python_api/numpy_reader.py
  tests/python_api/readers_test_file.sh
Labels: enhancement, ci:precheckin

#306 rocAL CMakeLists version check fix and rocDecode fix
  rocAL/CMakeLists.txt
  rocAL/source/loaders/video/video_loader.cpp
  tests/cpp_api/CMakeLists.txt
Labels: bug fix, ci:precheckin

#305 Test - Remove data files & readme updates
  data/videos/video_and_sequence_samples/labelled_videos/0/dino1_720p_30fps_1.mp4
  data/videos/video_and_sequence_samples/labelled_videos/0/dino1_720p_30fps_2.mp4
  data/videos/video_and_sequence_samples/labelled_videos/1/dino2_720p_30fps_1.mp4
  data/videos/video_and_sequence_samples/labelled_videos/1/dino2_720p_30fps_2.mp4
  data/videos/video_and_sequence_samples/labelled_videos/1/dino2_720p_30fps_3.mp4
  data/videos/video_and_sequence_samples/labelled_videos/2/dino3_720p_30fps_1.mp4
  data/videos/video_and_sequence_samples/labelled_videos/2/dino3_720p_30fps_2.mp4
  data/videos/video_and_sequence_samples/sequence/0/output_1.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_10.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_11.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_12.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_13.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_14.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_15.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_16.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_17.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_18.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_19.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_2.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_20.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_21.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_22.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_23.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_24.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_25.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_26.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_27.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_28.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_29.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_3.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_4.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_5.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_6.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_7.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_8.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_9.jpg
  data/videos/video_and_sequence_samples/sequence/0/output_90.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_30.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_31.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_32.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_33.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_34.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_35.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_36.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_37.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_38.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_39.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_40.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_41.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_42.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_43.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_44.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_45.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_46.jpg
  data/videos/video_and_sequence_samples/sequence/1/output_47.jpg
  data/videos/video_and_sequence_samples/test_frame/folder/test_frame_num.mp4
  data/videos/video_and_sequence_samples/test_frame/test_frame_num.txt
  data/videos/video_and_sequence_samples/test_timestamps/test_timestamps.mp4
  data/videos/video_and_sequence_samples/test_timestamps/test_timestamps.txt
  tests/cpp_api/video_tests/README.md
Labels: bug fix, ci:docs-only

#308 External CI: enable mainline branch trigger
  .azuredevops/rocm-ci.yml
Labels: enhancement

#307 Augmentation support - Transpose and Normalize
  rocAL/include/api/rocal_api_augmentation.h
  rocAL/include/augmentations/augmentations_nodes.h
  rocAL/include/augmentations/geometry_augmentations/node_transpose.h
  rocAL/source/api/rocal_api_augmentation.cpp
  rocAL/source/augmentations/effects_augmentations/node_normalize.cpp
  rocAL/source/augmentations/geometry_augmentations/node_transpose.cpp
  rocAL_pybind/amd/rocal/fn.py
  rocAL_pybind/rocal_pybind.cpp
  tests/cpp_api/unit_tests/testAllScripts.sh
  tests/cpp_api/unit_tests/unit_tests.cpp
Labels: enhancement, ci:precheckin
