Repository ROCm/rocAL, pull requests merged in 2025-01, with the labels that each got.

#254 Fix warnings with AMDClang++ compiler
  rocAL/include/api/rocal_api_augmentation.h
  rocAL/include/api/rocal_api_tensor.h
  rocAL/include/augmentations/geometry_augmentations/node_resize_mirror_normalize.h
  rocAL/include/decoders/image/fused_crop_decoder.h
  rocAL/include/decoders/image/hw_jpeg_decoder.h
  rocAL/include/decoders/video/hardware_video_decoder.h
  rocAL/include/loaders/audio/audio_loader.h
  rocAL/include/loaders/image/image_loader.h
  rocAL/include/loaders/image/image_read_and_decode.h
  rocAL/include/loaders/image/node_fused_jpeg_crop.h
  rocAL/include/loaders/image/node_fused_jpeg_crop_single_shard.h
  rocAL/include/meta_data/coco_meta_data_reader.h
  rocAL/include/meta_data/coco_meta_data_reader_key_points.h
  rocAL/include/meta_data/meta_data.h
  rocAL/include/meta_data/meta_node_crop.h
  rocAL/include/meta_data/meta_node_crop_mirror_normalize.h
  rocAL/include/meta_data/meta_node_flip.h
  rocAL/include/meta_data/meta_node_rotate.h
  rocAL/include/meta_data/meta_node_ssd_random_crop.h
  rocAL/include/parameters/parameter_crop.h
  rocAL/include/parameters/parameter_random_crop.h
  rocAL/include/parameters/parameter_random_crop_decoder.h
  rocAL/include/parameters/parameter_rocal_crop.h
  rocAL/include/pipeline/graph.h
  rocAL/include/pipeline/master_graph.h
  rocAL/include/pipeline/ring_buffer.h
  rocAL/include/pipeline/tensor.h
  rocAL/include/readers/file_source_reader.h
  rocAL/include/readers/image/caffe2_lmdb_record_reader.h
  rocAL/include/readers/image/caffe_lmdb_record_reader.h
  rocAL/include/readers/image/mxnet_recordio_reader.h
  rocAL/source/api/rocal_api_augmentation.cpp
  rocAL/source/api/rocal_api_meta_data.cpp
  rocAL/source/augmentations/effects_augmentations/node_normalize.cpp
  rocAL/source/augmentations/geometry_augmentations/node_crop.cpp
  rocAL/source/decoders/image/hw_jpeg_decoder.cpp
  rocAL/source/meta_data/randombboxcrop_reader.cpp
  rocAL/source/parameters/parameter_random_crop_decoder.cpp
  rocAL/source/pipeline/graph.cpp
  rocAL/source/pipeline/master_graph.cpp
  rocAL/source/pipeline/ring_buffer.cpp
  rocAL/source/pipeline/tensor.cpp
  rocAL_pybind/amd/rocal/fn.py
  rocAL_pybind/rocal_pybind.cpp
  tests/cpp_api/audio_tests/audio_tests.cpp
  tests/cpp_api/basic_test/basic_test.cpp
  tests/cpp_api/dataloader_multithread/dataloader_multithread.cpp
  tests/cpp_api/performance_tests_with_depth/performance_tests_with_depth.cpp
  tests/cpp_api/unit_tests/unit_tests.cpp
  tests/cpp_api/video_tests/video_tests.cpp
Labels: enhancement, bug fix, ci:precheckin

#259 Update LICENSE.txt to 2025
  LICENSE.txt
Labels: documentation, ci:docs-only

#250 Fused Crop resize support
  rocAL/include/api/rocal_api_augmentation.h
  rocAL/include/augmentations/geometry_augmentations/node_crop_resize.h
  rocAL/include/meta_data/meta_node_crop_resize.h
  rocAL/source/api/rocal_api_augmentation.cpp
  rocAL/source/augmentations/geometry_augmentations/node_crop_resize.cpp
  rocAL_pybind/amd/rocal/fn.py
  rocAL_pybind/amd/rocal/plugin/pytorch.py
  rocAL_pybind/rocal_pybind.cpp
  tests/python_api/pytorch_diffusion_loader.py
Labels: enhancement, ci:precheckin

#230 WebDataset Reader
  cmake/FindLibTar.cmake
  rocAL-setup.py
  rocAL/CMakeLists.txt
  rocAL/include/api/rocal_api_data_loaders.h
  rocAL/include/api/rocal_api_meta_data.h
  rocAL/include/api/rocal_api_types.h
  rocAL/include/helpers/tar_helper_functions.h
  rocAL/include/loaders/image/node_image_loader.h
  rocAL/include/loaders/image/node_image_loader_single_shard.h
  rocAL/include/meta_data/meta_data.h
  rocAL/include/meta_data/meta_data_reader.h
  rocAL/include/meta_data/webdataset_meta_data_reader.h
  rocAL/include/pipeline/commons.h
  rocAL/include/pipeline/master_graph.h
  rocAL/include/pipeline/tensor.h
  rocAL/include/readers/image/image_reader.h
  rocAL/include/readers/webdataset_source_reader.h
  rocAL/source/api/rocal_api_data_loaders.cpp
  rocAL/source/api/rocal_api_meta_data.cpp
  rocAL/source/helpers/tar_helper_functions.cpp
  rocAL/source/loaders/image/node_image_loader.cpp
  rocAL/source/loaders/image/node_image_loader_single_shard.cpp
  rocAL/source/meta_data/meta_data_reader_factory.cpp
  rocAL/source/meta_data/webdataset_meta_data_reader.cpp
  rocAL/source/pipeline/master_graph.cpp
  rocAL/source/readers/image/reader_factory.cpp
  rocAL/source/readers/webdataset_source_reader.cpp
  rocAL_pybind/amd/rocal/decoders.py
  rocAL_pybind/amd/rocal/pipeline.py
  rocAL_pybind/amd/rocal/plugin/pytorch.py
  rocAL_pybind/amd/rocal/readers.py
  rocAL_pybind/amd/rocal/types.py
  rocAL_pybind/rocal_pybind.cpp
  tests/cpp_api/unit_tests/testAllScripts.sh
  tests/cpp_api/unit_tests/unit_tests.cpp
  tests/python_api/unit_test.py
  tests/python_api/unit_tests.sh
Labels: enhancement, ci:precheckin

#255 Add webdataset reader python example and index file creation script
  CHANGELOG.md
  tests/python_api/parse_config.py
  tests/python_api/readers_test_file.sh
  tests/python_api/web_dataset_reader.py
  tools/README.md
  tools/im2rec.py
  tools/tar2idx.py
Labels: ci:precheckin

#264 Compiler - updates
  CMakeLists.txt
  README.md
  rocAL/CMakeLists.txt
  rocAL/rocAL_hip/CMakeLists.txt
  tests/cpp_api/CMakeLists.txt
  tests/cpp_api/audio_tests/CMakeLists.txt
  tests/cpp_api/basic_test/CMakeLists.txt
  tests/cpp_api/dataloader/CMakeLists.txt
  tests/cpp_api/dataloader_multithread/CMakeLists.txt
  tests/cpp_api/dataloader_tf/CMakeLists.txt
  tests/cpp_api/external_source/CMakeLists.txt
  tests/cpp_api/image_augmentation/CMakeLists.txt
  tests/cpp_api/performance_tests/CMakeLists.txt
  tests/cpp_api/performance_tests_with_depth/CMakeLists.txt
  tests/cpp_api/unit_tests/CMakeLists.txt
  tests/cpp_api/video_tests/CMakeLists.txt
Labels: enhancement, bug fix, ci:precheckin

#266 Update rocAL-setup.py & dockerfiles
  docker/README.md
  docker/rocal-on-ubuntu-20.dockerfile
  docker/rocal-on-ubuntu-22.dockerfile
  docker/rocal-with-pytorch.dockerfile
  docker/rocal-with-tensorflow.dockerfile
  rocAL-setup.py
Labels: enhancement, bug fix, ci:precheckin

#271 PyBind - Runtime Lib Fix
  CMakeLists.txt
  rocAL/CMakeLists.txt
  rocAL_pybind/CMakeLists.txt
Labels: enhancement, bug fix, ci:precheckin

#273 Setup - Updates
  CHANGELOG.md
  README.md
  rocAL-setup.py
Labels: enhancement, bug fix, ci:precheckin

#275 Setup - Audio RPM Req
  rocAL-setup.py
Labels: enhancement, bug fix, ci:precheckin
