Repository ROCm/rocAL, pull requests merged in 2025-07, with the labels that each got.

#353 Setup - Support Oracle OS
  README.md
  rocAL-setup.py
Labels: enhancement, ci:precheckin

#352 Find Package - Updates
  CMakeLists.txt
  README.md
  rocAL/CMakeLists.txt
  rocAL_pybind/CMakeLists.txt
  tests/cpp_api/CMakeLists.txt
Labels: enhancement, bug fix, ci:precheckin

#358 CHANGELOG Updates - ROCm 7.0.0
  CHANGELOG.md
Labels: bug fix, ci:docs-only

#351 Remove .jenkins
  .jenkins/common.groovy
  .jenkins/precheckin.groovy
Labels: ci:precheckin
