Repository ROCm/rocAL, pull requests merged in 2025-02, with the labels that each got.

#253 rocDecode integration in rocAL
  CHANGELOG.md
  CMakeLists.txt
  README.md
  cmake/FindrocDecode.cmake
  docs/user_guide/ch1.md
  rocAL/CMakeLists.txt
  rocAL/include/api/rocal_api_data_loaders.h
  rocAL/include/api/rocal_api_types.h
  rocAL/include/decoders/image/decoder.h
  rocAL/include/decoders/video/ffmpeg_video_decoder.h
  rocAL/include/decoders/video/hardware_video_decoder.h
  rocAL/include/decoders/video/rocdec_video_decoder.h
  rocAL/include/decoders/video/video_decoder.h
  rocAL/include/loaders/video/video_loader.h
  rocAL/include/loaders/video/video_read_and_decode.h
  rocAL/rocAL_hip/CMakeLists.txt
  rocAL/source/api/rocal_api_data_loaders.cpp
  rocAL/source/decoders/video/ffmpeg_video_decoder.cpp
  rocAL/source/decoders/video/hardware_video_decoder.cpp
  rocAL/source/decoders/video/rocdec_video_decoder.cpp
  rocAL/source/decoders/video/video_decoder_factory.cpp
  rocAL/source/loaders/video/video_loader.cpp
  rocAL/source/loaders/video/video_loader_sharded.cpp
  rocAL/source/loaders/video/video_read_and_decode.cpp
  rocAL/source/pipeline/master_graph.cpp
  rocAL_pybind/amd/rocal/readers.py
  rocAL_pybind/amd/rocal/types.py
  rocAL_pybind/getrocALwheelname.py
  rocAL_pybind/rocal_pybind.cpp
  rocAL_pybind/setup.py
  tests/cpp_api/video_tests/README.md
  tests/cpp_api/video_tests/testScript.sh
  tests/cpp_api/video_tests/video_tests.cpp
Labels: enhancement, ci:precheckin

#281 rocDecode - integration updates
  CHANGELOG.md
  CMakeLists.txt
  README.md
  cmake/FindrocDecode.cmake
  rocAL-setup.py
  rocAL/CMakeLists.txt
Labels: enhancement, ci:precheckin

#280 Adding numpy loaders
  rocAL/include/loaders/image/node_numpy_loader.h
  rocAL/include/loaders/image/node_numpy_loader_single_shard.h
  rocAL/include/loaders/image/numpy_loader.h
  rocAL/include/loaders/image/numpy_loader_sharded.h
  rocAL/include/pipeline/master_graph.h
  rocAL/include/readers/image/image_reader.h
  rocAL/source/loaders/image/node_numpy_loader.cpp
  rocAL/source/loaders/image/node_numpy_loader_single_shard.cpp
  rocAL/source/loaders/image/numpy_loader.cpp
  rocAL/source/loaders/image/numpy_loader_sharded.cpp
Labels: enhancement, ci:precheckin

#285 rocAL - rocDecode integration version check and fixes
  rocAL/CMakeLists.txt
  rocAL/include/decoders/image/decoder.h
  rocAL/include/decoders/video/rocdec_video_decoder.h
  rocAL/include/loaders/video/video_loader.h
  rocAL/rocAL_hip/CMakeLists.txt
  rocAL/source/decoders/video/rocdec_video_decoder.cpp
  rocAL/source/decoders/video/video_decoder_factory.cpp
  rocAL/source/loaders/video/video_loader.cpp
  rocAL_pybind/amd/rocal/types.py
  rocAL_pybind/rocal_pybind.cpp
Labels: bug fix, ci:precheckin

#279 gfx update
  CMakeLists.txt
  rocAL/CMakeLists.txt
Labels: enhancement, ci:precheckin

#290 Docs - refactored the landing page and TOC (#261)
  docs/conceptual/architecture.rst
  docs/conceptual/overview.rst
  docs/index.rst
  docs/sphinx/_toc.yml.in
  docs/sphinx/old_toc.yml.in
Labels: documentation, ci:docs-only

#267 rocAL C++ test suite fix
  rocAL/include/readers/file_source_reader.h
  rocAL/include/readers/image/caffe2_lmdb_record_reader.h
  rocAL/include/readers/image/caffe_lmdb_record_reader.h
  rocAL/include/readers/image/cifar10_data_reader.h
  rocAL/include/readers/image/coco_file_source_reader.h
  rocAL/include/readers/image/image_reader.h
  rocAL/include/readers/image/mxnet_recordio_reader.h
  rocAL/include/readers/image/tf_record_reader.h
  rocAL/include/readers/webdataset_source_reader.h
  rocAL/source/readers/file_source_reader.cpp
  rocAL/source/readers/image/caffe2_lmdb_record_reader.cpp
  rocAL/source/readers/image/caffe_lmdb_record_reader.cpp
  rocAL/source/readers/image/cifar10_data_reader.cpp
  rocAL/source/readers/image/coco_file_source_reader.cpp
  rocAL/source/readers/image/image_reader.cpp
  rocAL/source/readers/image/mxnet_recordio_reader.cpp
  rocAL/source/readers/image/tf_record_reader.cpp
  rocAL/source/readers/webdataset_source_reader.cpp
  rocAL_pybind/rocal_pybind.cpp
  tests/cpp_api/CMakeLists.txt
  tests/cpp_api/audio_tests/audio_tests.cpp
  tests/cpp_api/basic_test/basic_test.cpp
  tests/cpp_api/dataloader/README.md
  tests/cpp_api/dataloader/dataloader.cpp
  tests/cpp_api/dataloader_multithread/README.md
  tests/cpp_api/dataloader_multithread/dataloader_multithread.cpp
  tests/cpp_api/dataloader_tf/dataloader_tf.cpp
  tests/cpp_api/external_source/external_source.cpp
  tests/cpp_api/image_augmentation/CMakeLists.txt
  tests/cpp_api/image_augmentation/image_augmentation.cpp
  tests/cpp_api/performance_tests/performance_tests.cpp
  tests/cpp_api/performance_tests_with_depth/performance_tests_with_depth.cpp
  tests/cpp_api/unit_tests/pixel_comparison/image_comparison.py
  tests/cpp_api/unit_tests/unit_tests.cpp
  tests/cpp_api/video_tests/video_tests.cpp
  tests/python_api/image_comparison.py
Labels: bug fix, ci:precheckin
